// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemTaimsalDevs.DAL;

#nullable disable

namespace SystemTaimsalDevs.DAL.Migrations
{
    [DbContext(typeof(SystemTaimsalDevsContext))]
    [Migration("20230217182327_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SystemTaimsalDevs.EL.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClient"));

                    b.Property<string>("NameClient")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdClient")
                        .HasName("PK__Client__Taimsal_001");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("SystemTaimsalDevs.EL.Machine", b =>
                {
                    b.Property<int>("IdMachine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMachine"));

                    b.Property<string>("ImageMachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameMachine")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdMachine")
                        .HasName("PK__Machine__Taimsal__001");

                    b.ToTable("Machine");
                });

            modelBuilder.Entity("SystemTaimsalDevs.EL.Product", b =>
                {
                    b.Property<int>("IdProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduct"));

                    b.Property<string>("DescriptionProduct")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageProduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameProduct")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("IdProduct")
                        .HasName("PK__Product__Taimsal_001");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("SystemTaimsalDevs.EL.Provider", b =>
                {
                    b.Property<int>("IdProvider")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProvider"));

                    b.Property<string>("NameProvider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("IdProvider")
                        .HasName("PK__Provider__Taimsal__001");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("SystemTaimsalDevs.EL.Report", b =>
                {
                    b.Property<int>("IdReport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReport"));

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<int?>("IdMachine")
                        .HasColumnType("int");

                    b.Property<int?>("IdProduct")
                        .HasColumnType("int");

                    b.Property<int?>("IdProvider")
                        .HasColumnType("int");

                    b.Property<int?>("IdUser")
                        .HasColumnType("int");

                    b.HasKey("IdReport")
                        .HasName("PK__Report__001");

                    b.HasIndex(new[] { "IdClient" }, "IX_Report_IdClient");

                    b.HasIndex(new[] { "IdMachine" }, "IX_Report_IdMachine");

                    b.HasIndex(new[] { "IdProduct" }, "IX_Report_IdProduct");

                    b.HasIndex(new[] { "IdProvider" }, "IX_Report_IdProvider");

                    b.HasIndex(new[] { "IdUser" }, "IX_Report_IdUser");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("SystemTaimsalDevs.EL.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NameRol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdRol")
                        .HasName("PK__Rol__TaimsalDev_001");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("SystemTaimsalDevs.EL.UserDev", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("LastNameUser")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("NameUser")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nchar(32)")
                        .IsFixedLength();

                    b.Property<DateTime>("RegistrationUser")
                        .HasColumnType("datetime2");

                    b.Property<byte>("StatusUser")
                        .HasColumnType("tinyint")
                        .HasColumnName("Status_User");

                    b.HasKey("IdUser")
                        .HasName("PK__User__Taimsal__001");

                    b.HasIndex(new[] { "IdRol" }, "IX_UserDevs_IdRol");

                    b.ToTable("UserDevs");
                });

            modelBuilder.Entity("SystemTaimsalDevs.EL.Report", b =>
                {
                    b.HasOne("SystemTaimsalDevs.EL.Client", "IdClientNavigation")
                        .WithMany("Reports")
                        .HasForeignKey("IdClient")
                        .IsRequired()
                        .HasConstraintName("FK2__Clients__Report");

                    b.HasOne("SystemTaimsalDevs.EL.Machine", "IdMachineNavigation")
                        .WithMany("Reports")
                        .HasForeignKey("IdMachine")
                        .HasConstraintName("FK5_Machine__Report__001");

                    b.HasOne("SystemTaimsalDevs.EL.Product", "IdProductNavigation")
                        .WithMany("Reports")
                        .HasForeignKey("IdProduct")
                        .HasConstraintName("FK4__Products__Report");

                    b.HasOne("SystemTaimsalDevs.EL.Provider", "IdProviderNavigation")
                        .WithMany("Reports")
                        .HasForeignKey("IdProvider")
                        .HasConstraintName("FK3__Provider__Report__001");

                    b.HasOne("SystemTaimsalDevs.EL.UserDev", "IdUserNavigation")
                        .WithMany("Reports")
                        .HasForeignKey("IdUser")
                        .HasConstraintName("FK1__User__Report");

                    b.Navigation("IdClientNavigation");

                    b.Navigation("IdMachineNavigation");

                    b.Navigation("IdProductNavigation");

                    b.Navigation("IdProviderNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("SystemTaimsalDevs.EL.UserDev", b =>
                {
                    b.HasOne("SystemTaimsalDevs.EL.Rol", "IdRolNavigation")
                        .WithMany("UserDevs")
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("FK1__Rol__User__001");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("SystemTaimsalDevs.EL.Client", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("SystemTaimsalDevs.EL.Machine", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("SystemTaimsalDevs.EL.Product", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("SystemTaimsalDevs.EL.Provider", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("SystemTaimsalDevs.EL.Rol", b =>
                {
                    b.Navigation("UserDevs");
                });

            modelBuilder.Entity("SystemTaimsalDevs.EL.UserDev", b =>
                {
                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
